SET MODE PostgreSQL;
--
--CREATE TABLE IF NOT EXISTS feedback (
--id int PRIMARY KEY auto_increament,
--name VARCHAR,
--email VARCHAR,
--message VARCHAR
--);
--
--CREATE TABLE IF NOT EXISTS specifications (int serial PRIMARY KEY, designSpace VARCHAR
--);SE